model:
  filename: ./gen/models_gen.go
client:
  filename: ./gen/client.go
models:
  Int:
    model: github.com/99designs/gqlgen/graphql.Int64
  DateTime:
    model: github.com/99designs/gqlgen/graphql.Time
schema:
  - "./schema/*.graphqls"
query:
  - "./query/*.graphql"
generate:
  suffix:
    mutation: Payload
  prefix:
    mutation: Hoge
  clientV2: true
